accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('<int:user_pk>/change_password/', views.change_password, name='change_password'),
    path('profile/<str:username>', views.profile, name='profile'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
]

articles/urls.py
from django.urls import path
from . import views

app_name='articles'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/update/', views.update, name='update'),
    
    # 댓글
    path('<int:pk>/comments/', views.create_comment, name='create_comment'),
    path(
        '<int:article_pk>/comments/<int:comment_pk>/',
        views.delete_comment,
        name='delete_comment',
    ),

    # 게시글 좋아요
    path('<int:article_pk>/likes/', views.likes, name='likes'),

    # 해시태그
    path('<int:hash_pk>/hashtag/', views.hashtag, name='hashtag'),

]

crud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
# User 모델은 커스텀 해야 함

# 프로젝트 settings에 
# AUTH_USER_MODEL = 'accounts.User' 설정하는 것 잊지말기 
class User(AbstractUser):
    followings = models.ManyToManyField("self", symmetrical=False, related_name="followers")

    def __str__(self):
        return self.username

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()


class CustomUserChangeForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        model = get_user_model()

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.views.decorators.http import require_POST, require_http_methods
from django.contrib.auth.decorators import login_required
from .forms import CustomUserChangeForm, CustomUserCreationForm

def login(request):
    if request.user.is_authenticated:
        return redirect('articles:index')

    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        # form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect(request.GET.get('next') or 'articles:index')
    else:
        form = AuthenticationForm()
    context = {
        'form': form
    }
    return render(request, 'accounts/login.html', context)


@login_required
def logout(request):
    if request.user.is_authenticated:
        auth_logout(request)
        return redirect('articles:index')
    

def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            return redirect('articles:index')
    else:
        form = CustomUserCreationForm()
    context ={
        'form' : form,
    }
    return render(request, 'accounts/signup.html', context)


@login_required
def delete(request):
    user = request.user
    user.delete()
    return redirect('articles:index')


@login_required
def update(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('articles:index')
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/update.html', context)


@login_required
def change_password(request, user_pk):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            # 비밀번호 바뀌어도 로그인 상태 유지
            update_session_auth_hash(request, user) 
            return redirect('articles:index')
        
    # GET요청으로 들어오면 form을 보여준다
    else:
        form = PasswordChangeForm(request.user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/change_password.html', context)


@login_required
def profile(request, username):
    # User의 detail 페이지
    # User를 먼저 조회
    User = get_user_model()
    person = User.objects.get(username=username)
    context = {
        'person' : person,
    }
    return render(request, 'accounts/profile.html', context)


@login_required
def profile(requets, username):
    User = get_user_model()
    person = User.objects.get(username=username)
    context = {
        'person' : person,
    }
    return render(requets, 'accounts/profile.html', context)


@login_required
def follow(request, user_pk):
    # follow하고 있는 대상을 조회
    User = get_user_model()
    you = User.objects.get(pk=user_pk)
    me = request.user

    if you != me:
        # 내가 상대방의 팔로워 목록에 있다면
        if me in you.followers.all():
            # 팔로우 취소
            me.followings.remove(you)
        
        else:
            me.followings.add(you)
        
    return redirect('accounts:profile', you.username)

accounts/templates/accounts/change_password.html
{% extends "base.html" %}

{% block content %}
<h1>비밀번호 변경</h1>
<form action="{% url "accounts:change_password" user.pk %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
</form>
{% endblock content %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
  <h1>로그인</h1>
  <form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
  </form>
{% endblock content %}

accounts/templates/accounts/profile.html
{% extends "base.html" %}

{% block content %}
    <a href="{% url "articles:index" %}">뒤로 가기</a>
    <h3>{{ person.username }}님의 프로필(੭˙ ˘ ˙)੭</h3>

    <div>
        <div>
            팔로잉: {{ person.followings.all|length }}명<br>
            팔로워: {{ person.followers.all|length }}명
        </div>

        {% comment %} person은 프로필 주인, request.user은 요청을 보내는 나! {% endcomment %}
        {% comment %} 팔로우 요청 보내기 {% endcomment %}
        <div>
            {% if request.user != person %}
                <form action="{% url "accounts:follow" person.pk %}" method="POST">
                    {% csrf_token %}
                    {% if request.user in person.followers.all %}
                        <input type="submit" value="언팔로우">
                    {% else %}
                        <input type="submit" value="팔로우">
                    {% endif %}
                </form>
            {% endif %}
        </div>

        <hr>
        {% comment %} 작성한 게시글, 댓글, 좋아요 누른 게시글 확인 {% endcomment %}
        <div>
            <strong>작성한 게시글</strong> 
            {% for article in person.articles.all %}
                <p> {{article.title}} </p>
            {% endfor %}
        </div>

        <hr>
        <div>
            <strong>작성한 댓글</strong> 
            {% for comment in person.comments.all %}
                <p> {{ comment.content }} </p>
            {% endfor %}
        </div>

        <hr>
        <div>
            <strong>좋아요를 누른 게시글</strong>
            {% for article in person.like_articles.all %}
                <p>{{ article.title }}</p>
            {% endfor %}
        </div>
    </div>
{% endblock content %}

accounts/templates/accounts/signup.html
{% extends "base.html" %}

{% block content %}
<h1>회원가입</h1>
<form action="{% url "accounts:signup" %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
</form>
{% endblock content %}