accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('<int:user_pk>/change_password/', views.change_password, name='change_password'),
    path('profile/<str:username>', views.profile, name='profile'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
]

articles/urls.py
from django.urls import path
from . import views

app_name='articles'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/update/', views.update, name='update'),
    
    # 댓글
    path('<int:pk>/comments/', views.create_comment, name='create_comment'),
    path(
        '<int:article_pk>/comments/<int:comment_pk>/',
        views.delete_comment,
        name='delete_comment',
    ),

    # 게시글 좋아요
    path('<int:article_pk>/likes/', views.likes, name='likes'),

    # 해시태그
    path('<int:hash_pk>/hashtag/', views.hashtag, name='hashtag'),

]

crud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
]

articles/models.py
from django.db import models
from taggit.managers import TaggableManager
from django.conf import settings

class Hashtag(models.Model):
    content = models.CharField(max_length=100, unique=True)

# Create your models here.
class Article(models.Model):
    # 작성자를 외래키로 설정
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="articles")
    # N:M
    like_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name='like_articles'
    )
    hashtags = models.ManyToManyField(
        Hashtag, 
        related_name='articles'
    )

    # fields
    title = models.CharField(max_length=100)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    tag = TaggableManager()
    
    def __str__(self):
        return self.title
    

class Comment(models.Model):
    # 어떤 글에 댓글을 작성할지? -> 글을 외래키로 설정
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name="comments")
    # 작성자를 외래키로 설정
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    # N:M
    like_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name='like_comments'
    )
    # fields
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

articles/forms.py
from django import forms
from .models import Article, Comment


class ArticleForm(forms.ModelForm):
    title = forms.CharField(
        label='제목',
        widget=forms.TextInput(
            attrs={
                'class': 'my-title form-control',
                'placeholder': '기가막힌제목',
                'maxlength': 10,
            }
        )
    )
    content = forms.CharField(
        label='내용',
        widget=forms.Textarea(
            attrs={
                'class': 'my-content form-control',
                'placeholder': '놀라운내용',
                'rows': 5,
                'cols': 50,
            }
        ),
        error_messages={
            'required': '빈내용은 안돼!!!'
        }
    )

    class Meta:
        model = Article
        exclude = ('user', 'like_users', 'hashtags',)
        
        
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)

articles/views.py
from django.shortcuts import render, redirect
from django.shortcuts import get_object_or_404
from django.views.decorators.http import require_http_methods, require_POST, require_safe
from .models import Article, Comment, Hashtag
from .forms import ArticleForm, CommentForm
from django.contrib.auth.decorators import login_required


#  전체 게시글 조회
def index(request):
    articles = Article.objects.order_by('-pk')
    context = {
        'articles' : articles,
    }
    return render(request, 'articles/index.html', context)


# 특정 게시물 조회
def detail(request, pk):
    article = get_object_or_404(Article, pk=pk) # 없으면 404 에러
    comment_form = CommentForm()
    comments = article.comments.all() # article에 해당되는 comments 출력
    hashtags = article.hashtags.all() # article에 해당되는 hashtags 출력
    context = {
        'article' : article,
        'comment_form' : comment_form,
        'comments' : comments,
        'hashtags' : hashtags,
    }
    return render(request, 'articles/detail.html', context)


# 게시물 작성
@login_required
def create(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST)
        if form.is_valid():
            article = form.save(commit=False)
            article.user = request.user
            # 통일성을 위해 
            # article.save()보단 form.save()로!
            form.save_m2m()
            return redirect('articles:detail', article.pk)
    else:
        form = ArticleForm()
    context = {
        'form' : form,
    }
    return render(request, 'articles/create.html', context)


# 게시물 삭제
@login_required
def delete(request, pk):
    article = Article.objects.get(pk=pk) 
    if request.user == article.user:
        article.delete()
    return redirect('articles:index')


# 게시물 수정
@login_required
def update(request, pk):
    article = get_object_or_404(Article, pk=pk)
    # 게시물 작성자가 로그인된 유저라면
    if request.user == article.user:
        # POST 요청일 때
        if request.method == 'POST':
            form = ArticleForm(request.POST, instance=article)
            if form.is_valid():
                form.save()
                return redirect('articles:detail', article.pk)
        # GET 요청일 때
        else:
            form = ArticleForm(instance=article)
    
    # 게시물 작성자가 로그인된 유저와 다르다면
    else:
        return redirect('articles:detail', article.pk)
    
    context = {
        'form': form,
        'article': article,
    }
    return render(request, 'articles/update.html', context)


# 댓글 작성
@login_required
def create_comment(request, pk):
    article = Article.objects.get(pk=pk)
    comment_form = CommentForm(request.POST)
    
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.article = article
        comment.user = request.user
        comment_form.save()
        return redirect('articles:detail', article.pk)

    context={
        'article' : article,
        'comment_form' : comment_form,    
    }
    return render(request, 'article/detail.html', context)


# 댓글 삭제
@login_required
def delete_comment(request, article_pk, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)
    if request.user == comment.user:
        comment.delete()
    return redirect('articles:detail', article_pk)


# 게시글 좋아요
@login_required
def likes(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    # get은 찾는 객체가 없다면 에러를 반환
    # +단일 객체를 반환
    # if request.user in article.like_users.all():
    # filter는 여러개의 객체가 담긴 QuerySet으로 반환
    if article.like_users.filter(pk=request.user.pk).exists():
        article.like_users.remove(request.user)
    else:
        article.like_users.add(request.user)
    return redirect('articles:index')


# 해시태그
def hashtag(request, hash_pk):
    hashtag = Hashtag.objects.get(pk=hash_pk)
    articles = hashtag.articles.all()
    context = {
        'hashtag' : hashtag,
        'articles' : articles,
    }
    return render(request, 'articles/hashtag.html', context)

articles/templates/articles/create.html
{% extends "base.html" %}

{% block content %}
    <h3>글 쓰기</h3>
    <div class="container">
        <form action="{% url 'articles:create' %}" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="작성">
        </form>
    </div>
    <hr>
    <a href="{% url 'articles:index' %}">뒤로 가기</a>
{% endblock content %}

articles/templates/articles/detail.html
{% extends "base.html" %}

{% block content %}

<div class="container p-3">
  
  <div class="row">
    <h3> {{ article.pk }}번째 글 </h3>
    <hr>
    <p>작성자 : 
      <a href="{% url "accounts:profile" article.user.username %}">{{ article.user }}</a>
    </p>
    <p>제목 : {{ article.title }}</p>
    <p>내용 : {{ article.content }}</p>
    <p>언제썼냐면 : {{ article.created_at }}</p>
    <p>수정은언제 : {{ article.updated_at }}</p>
    <p>해시태그 : 
      {% for hashtag in hashtags %}
        {{ hashtag.content }}
      {% endfor %} 
    </p>
  </div>

  {% comment %} 수정, 삭제, 뒤로가기 {% endcomment %}
  <div class="row">
    {% comment %} 글 작성자가 로그인한 사용자라면 삭제 버튼 표시 {% endcomment %}
    {% if article.user == request.user %}
    <a href="{% url 'articles:update' article.pk %}">수정하기</a>
    <form action="{% url 'articles:delete' article.pk %}" method="POST">
      {% csrf_token %}
      <button>삭제하기</button>
    </form>
    {% endif %}
    <a href="{% url 'articles:index' %}">뒤로가기</a>
  </div>

  <hr>
  
  <div class="row">
    <h3>댓글 목록</h3>
    {% for comment in comments %}
      <div>{{ comment.user }}: {{ comment.content }}</div>

      {% comment %} 댓글 작성자가 로그인한 사용자라면 삭제 버튼 표시 {% endcomment %}
      {% if comment.user == request.user %}
        <form action="{% url "articles:delete_comment" article.pk comment.pk %}" method="POST">
          {% csrf_token %}
          <input type="submit" value="댓글삭제">
        </form>
      {% endif %}
    {% endfor %}

    <form action="{% url "articles:create_comment" article.pk %}" method="POST">
      {% csrf_token %}
      {{ comment_form }}
      <input type="submit" value="댓글작성">
    </form>
  </div>

  <hr>

</div>

{% endblock content %}

articles/templates/articles/hashtag.html
{% extends "base.html" %}

{% block content %}
    <h3> {{ articles.count }}개의 게시글 </h3>
    <hr>
    <p> {{ hashtag.content }}을(를) 태그한 글 </p>
    {% for article in articles %}
        <h4> {{ article.pk }}번 게시글 </h4>
        <p> 게시글 {{ article.title }} </p>
        <p> {{ article.comments.all.count }}개 댓글 </p>
        <a href="{% url "articles:detail" article.pk %}">상세글</a>
        <hr>
    {% endfor %}
{% endblock content %}

articles/templates/articles/index.html
{% extends "base.html" %}

{% block content %}
<h1>게시글</h1>
{% if request.user.is_authenticated %}
    <a href="{% url "articles:create" %}">글 쓰기</a>
{% endif %}
<hr>
{% for article in articles %}
    <p>{{ article.pk }}번째 글</p>
    <p>{{ article.like_users.all|length }}명이 좋아합니다!</p>
    <p>제목: {{article.title}}</p>
    <p>내용: {{article.content}}</p>
    <a href="{% url "articles:detail" article.pk %}">자세히 보기</a>
    <form action="{% url "articles:likes" article.pk %}" method="POST">
        {% csrf_token %}
        {% if request.user in article.like_users.all %}
            <input type="submit" value="좋아요,,취솜">
        {% else %}
            <input type="submit" value="좋아요">
        {% endif %}
    </form>
    <hr>
{% endfor %}
{% endblock content %}

articles/templates/articles/update.html
{% extends 'base.html' %}

{% block content %}
  <h1>수정하기</h1>
  <div class="container">
    <div class="row">
      <form action="{% url 'articles:update' article.pk %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="수정하기">
      </form>
    </div>
  </div>
  <hr>
  <a href="{% url 'articles:detail' article.pk %}">뒤로가기</a>
{% endblock  %}