accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('<int:user_pk>/change_password/', views.change_password, name='change_password'),
    path('profile/<str:username>', views.profile, name='profile'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
]

crud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
]

templates/base.html
{% load bootstrap5 %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% bootstrap_css %}
    <title>빛나는 소나무</title>
    <link rel="stylesheet" href="{% static "css/style.css" %}">
</head>
<body>
    <div class="container p-3">
        {% comment %} 로그인된 상태일 때 {% endcomment %}
        {% if request.user.is_authenticated %}
            <h3>안녕, 
                <a href="{% url "accounts:profile" request.user.username %}"> {{ user }} </a>   
            </h3>
            <a href="{% url "accounts:update" %}">회원정보 수정</a>
            <form action="{% url "accounts:logout" %}" method="POST">
                {% csrf_token %}
                <input type="submit" value="로그아웃">
            </form>
        {% comment %} 로그인이 안된 상태일 때 {% endcomment %}
        {% else %}
            <a href="{% url "accounts:login" %}">로그인</a>
            <a href="{% url "accounts:signup" %}">회원가입</a>
        {% endif %}
    </div>
    {% block content %}
    {% endblock content %}
    <div class="container">
        <form action="{% url "accounts:delete" %}" method="POST">
            {% csrf_token %}
            {% if request.user.is_authenticated %}
            <input type="submit" value="계정 삭제ㅠㅠ">
            {% endif %}
            </form>
    </div>
    {% bootstrap_javascript %}
</body>
</html>